export const quizData = [
  {
    id: 1,
    level: 'A',
    question: `q1`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 2,
    level: 'A',
    question: `q2`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 3,
    level: 'A',
    question: `q3`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 4,
    level: 'A',
    question: `q4`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 5,
    level: 'A',
    question: `q5`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 6,
    level: 'A',
    question: `q6`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 7,
    level: 'A',
    question: `q7`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 8,
    level: 'A',
    question: `q8`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 9,
    level: 'A',
    question: `q9`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 10,
    level: 'A',
    question: `q10`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 11,
    level: 'A',
    question: `q11`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 12,
    level: 'A',
    question: `q12`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 1,
    level: 'B',
    question: `q13`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 2,
    level: 'B',
    question: `q14`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 3,
    level: 'B',
    question: `q15`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 4,
    level: 'B',
    question: `q16`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 5,
    level: 'B',
    question: `q17`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 6,
    level: 'B',
    question: `q18`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 7,
    level: 'B',
    question: `q19`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 8,
    level: 'B',
    question: `q20`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 9,
    level: 'B',
    question: `q21`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 10,
    level: 'B',
    question: `q22`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 11,
    level: 'B',
    question: `q23`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 12,
    level: 'B',
    question: `q24`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 1,
    level: 'C',
    question: `q25`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 8,
  },
  {
    id: 2,
    level: 'C',
    question: `q26`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 2,
  },
  {
    id: 3,
    level: 'C',
    question: `q27`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 3,
  },
  {
    id: 4,
    level: 'C',
    question: `q28`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 8,
  },
  {
    id: 5,
    level: 'C',
    question: `q29`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 7,
  },
  {
    id: 6,
    level: 'C',
    question: `q30`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 4,
  },
  {
    id: 7,
    level: 'C',
    question: `q31`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 5,
  },
  {
    id: 8,
    level: 'C',
    question: `q32`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 1,
  },
  {
    id: 9,
    level: 'C',
    question: `q33`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 7,
  },
  {
    id: 10,
    level: 'C',
    question: `q34`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 6,
  },
  {
    id: 11,
    level: 'C',
    question: `q35`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 1,
  },
  {
    id: 12,
    level: 'C',
    question: `q36`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 2,
  },
  {
    id: 1,
    level: 'D',
    question: `q37`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 3,
  },
  {
    id: 2,
    level: 'D',
    question: `q38`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 4,
  },
  {
    id: 3,
    level: 'D',
    question: `q39`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 3,
  },
  {
    id: 4,
    level: 'D',
    question: `q40`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 7,
  },
  {
    id: 5,
    level: 'D',
    question: `q41`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 8,
  },
  {
    id: 6,
    level: 'D',
    question: `q42`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 6,
  },
  {
    id: 7,
    level: 'D',
    question: `q43`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 5,
  },
  {
    id: 8,
    level: 'D',
    question: `q44`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 4,
  },
  {
    id: 9,
    level: 'D',
    question: `q45`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 1,
  },
  {
    id: 10,
    level: 'D',
    question: `q46`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 2,
  },
  {
    id: 11,
    level: 'D',
    question: `q47`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 5,
  },
  {
    id: 12,
    level: 'D',
    question: `q48`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 6,
  },
  {
    id: 1,
    level: 'E',
    question: `q49`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 7,
  },
  {
    id: 2,
    level: 'E',
    question: `q50`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 6,
  },
  {
    id: 3,
    level: 'E',
    question: `q51`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 8,
  },
  {
    id: 4,
    level: 'E',
    question: `q52`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 2,
  },
  {
    id: 5,
    level: 'E',
    question: `q53`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 1,
  },
  {
    id: 6,
    level: 'E',
    question: `q54`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 5,
  },
  {
    id: 7,
    level: 'E',
    question: `q55`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 1,
  },
  {
    id: 8,
    level: 'E',
    question: `q56`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 6,
  },
  {
    id: 9,
    level: 'E',
    question: `q57`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 3,
  },
  {
    id: 10,
    level: 'E',
    question: `q58`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 2,
  },
  {
    id: 11,
    level: 'E',
    question: `q59`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 4,
  },
  {
    id: 12,
    level: 'E',
    question: `q60`,
    variants: ['1', '2', '3', '4', '5', '6', '7', '8'],
    true: 5,
  },
];
