export const quizData = [
  {
    id: 1,
    level: 'A',
    question: `q1`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 2,
    level: 'A',
    question: `q2`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 3,
    level: 'A',
    question: `q3`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 4,
    level: 'A',
    question: `q4`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 5,
    level: 'A',
    question: `q5`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 6,
    level: 'A',
    question: `q6`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 7,
    level: 'A',
    question: `q7`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 8,
    level: 'A',
    question: `q8`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 9,
    level: 'A',
    question: `q9`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 10,
    level: 'A',
    question: `q10`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 11,
    level: 'A',
    question: `q11`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 12,
    level: 'A',
    question: `q12`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 1,
    level: 'B',
    question: `q13`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 2,
    level: 'B',
    question: `q14`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 3,
    level: 'B',
    question: `q15`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 4,
    level: 'B',
    question: `q16`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 2,
  },
  {
    id: 5,
    level: 'B',
    question: `q17`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 1,
  },
  {
    id: 6,
    level: 'B',
    question: `q18`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 7,
    level: 'B',
    question: `q19`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
  {
    id: 8,
    level: 'B',
    question: `q20`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 6,
  },
  {
    id: 9,
    level: 'B',
    question: `q21`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 10,
    level: 'B',
    question: `q22`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 3,
  },
  {
    id: 11,
    level: 'B',
    question: `q23`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 4,
  },
  {
    id: 12,
    level: 'B',
    question: `q24`,
    variants: ['1', '2', '3', '4', '5', '6'],
    true: 5,
  },
];
